services:
  - type: web
    name: web-scraper-api
    env: python
    plan: free
    region: oregon 
    buildCommand: |
      rm -rf ~/.cache/ms-playwright      # limpia navegadores antiguos
      pip install -r requirements.txt     # instala dependencias
      playwright install                  # descarga navegadores
      ls ~/.cache/ms-playwright           # verifica instalación
    # startCommand: "PLAYWRIGHT_BROWSERS_PATH=0 fastapi run src/main.py --host 0.0.0.0 --port $PORT"
    startCommand: PLAYWRIGHT_BROWSERS_PATH=0 PYTHONPATH=./src uvicorn src.main:app --host 0.0.0.0 --port $PORT