services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    region: oregon 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: "10000"  # No es obligatorio, Render lo asigna automáticamente
