services:
  - type: web
    name: web-scraper-api
    env: python
    plan: free
    region: oregon 
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: PYTHONPATH=./src uvicorn src.main:app --host 0.0.0.0 --port $PORT
