services:
  - type: web
    name: web-scraper-api
    env: python
    plan: free
    region: oregon 
    buildCommand: |
      pip install -r requirements.txt && playwright install
      ls ~/.cache/ms-playwright
    startCommand: "PLAYWRIGHT_BROWSERS_PATH=0 fastapi run src/main.py --host 0.0.0.0 --port $PORT"