services:
  - type: web
    name: web-scraper-api
    env: python
    plan: free
    region: oregon 
    buildCommand: pip install -r requirements.txt && playwright install --with-deps
    startCommand: "fastapi run src/main.py --host 0.0.0.0 --port $PORT"